QCRSFC/HL null distributions:   0%|          | 0/10000 [00:00<?, ?it/s]QCRSFC/HL null distributions:   0%|          | 1/10000 [00:05<15:13:41,  5.48s/it]QCRSFC/HL null distributions:   0%|          | 12/10000 [00:05<1:17:27,  2.15it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/analysis.py", line 283, in _other_null_iter
    perm_qcrsfc_zs = qcrsfc_analysis(perm_mean_qc, z_corr_mats)
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/analysis.py", line 174, in qcrsfc_analysis
    assert z_corr_mats.ndim == 2, z_corr_mats.ndim
AttributeError: 'list' object has no attribute 'ndim'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/experiment-1/05_resp_and_fc.py", line 213, in <module>
    target_file_pattern,
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/experiment-1/05_resp_and_fc.py", line 167, in run_ddmra_of_mean_rvt
    analyses=("qcrsfc", "highlow"),
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/workflows.py", line 262, in run_analyses
    n_jobs=n_jobs,
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/analysis.py", line 343, in other_null_distributions
    for seed in range(n_iters)
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'list' object has no attribute 'ndim'
